title: SG101
url: ""
favicon: /images/SG101sq.png
colors:
  primary-color: "#323594"
  secondary-color: "#4a90e2"
  media-colors:
    - title: media-color-one
      color: "#ED7D31"
    - title: media-color-two
      color: "#4a90e2"
    - title: media-color-three
      color: "#9b9b9b"
    - title: media-color-four
      color: "#00838f"
    - title: media-color-five
      color: "#b21238"
resources_name: resources
description: "An Isomer site of the Singapore Government "
permalink: none
baseurl: ""
exclude:
  - travis-script.js
  - .travis.yml
  - README.md
  - package.json
  - package-lock.json
  - node_modules
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/
  - Gemfile
  - Gemfile.lock
include:
  - _redirects
defaults:
  - scope:
      path: ""
    values:
      layout: page
custom_css_path: /misc/custom.css
custom_print_css_path: /assets/css/print.css
paginate: 12
remote_theme: isomerpages/isomerpages-template@next-gen
safe: false
plugins:
  - jekyll-feed
  - jekyll-assets
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-remote-theme
staging: https://mindef-connexion-staging.netlify.app
prod: https://mindef-connexion-prod.netlify.app
is_government: true
shareicon: /images/SG101sq.png
